//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ForTeddyArcade : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.forTeddyArcade_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.forTeddyArcade_Look;
            }
        }
        
        public virtual SteamVR_Action_Boolean Exit
        {
            get
            {
                return SteamVR_Actions.forTeddyArcade_Exit;
            }
        }
        
        public virtual SteamVR_Action_Vibration VibrationL
        {
            get
            {
                return SteamVR_Actions.forTeddyArcade_VibrationL;
            }
        }
        
        public virtual SteamVR_Action_Vibration VibrationR
        {
            get
            {
                return SteamVR_Actions.forTeddyArcade_VibrationR;
            }
        }
    }
}
