//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ForTeddyVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Grab;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Look;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Run
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Run;
            }
        }
        
        public virtual SteamVR_Action_Boolean Focus
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_Focus;
            }
        }
        
        public virtual SteamVR_Action_Vibration VibrationL
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_VibrationL;
            }
        }
        
        public virtual SteamVR_Action_Vibration VibrationR
        {
            get
            {
                return SteamVR_Actions.forTeddyVR_VibrationR;
            }
        }
    }
}
